---
- name: Converge
  hosts: all

  tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=3600
    - name: Install npm
      apt:
        pkg: npm
    - name: Include this role
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
